[package]
name = "derive"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
internal = { path = "../internal" }
quote = "0.6.12"
syn = "0.15.33"
proc-macro2 = "0.4.29"
heck = "0.3.1"
